modLoader = "javafml"
loaderVersion = "${neoforgeLoaderRange}"
license = "All Rights Reserved"

[[mixins]]
config = "${id}.mixins.json"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = "${description}"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "jei"
type = "required"
versionRange = "[${jeiVersion},)"
ordering = "AFTER"
side = "CLIENT"
